#! /usr/bin/env bash
export ME=$(whoami)
echo "#############################"
echo "# Entering superuser space..."
echo "# Updating apt sources to sid"
su - -c "echo | tee /etc/apt/sources.list << EOF
deb http://deb.debian.org/debian/ sid main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian/ sid main contrib non-free non-free-firmware
EOF"
echo "# DONE!"
echo "# Upgrading system to sid"
su - -c "\
  ME='$ME'
  apt update \
  && apt full-upgrade --yes \
  && echo '# DONE!' \
  && echo '# Installing sudo and adding user to sudoers' \
  && apt install sudo --yes \
  && usermod -aG sudo '$ME' \
  && echo '# DONE!' \
"
echo "# ...exiting superuser space."
echo "#############################"
echo "# Installing packages with apt"
su -l $ME -c "\
  sudo -S apt update \
  && sudo apt upgrade --yes \
  && sudo apt install --yes curl fish tmux neovim git podman openvpn openresolv clang \
  && sudo apt install --yes xinit lxdm awesome wireplumber pipewire-pulse alacritty firefox vlc \
  && if lspci | grep -q NVIDIA; then sudo apt install --yes linux-headers-amd64 nvidia-driver nvidia-xconfig nvidia-cuda-dev nvidia-cuda-toolkit; fi \
  && sudo apt clean --yes \
  && sudo apt autoclean --yes \
  && sudo apt autoremove --purge --yes \
  && echo '# Adding fish to shells' \
  && echo /usr/bin/fish | sudo tee -a /etc/shells \
"
echo "# DONE!" 
echo "# Installing Ollama"
su -l $ME -c "\
  curl -L 'https://ollama.com/download/ollama-linux-amd64.tgz' -o ollama.tgz \
  && sudo -S tar -C /usr -xzf ollama.tgz \
  && rm ollama.tgz \
"
echo "# DONE!"
echo "# Installing uv"
curl -LsSf https://astral.sh/uv/install.sh | sh
echo "# DONE!"
echo "# Installing ruff"
curl -LsSf https://astral.sh/ruff/install.sh | sh
echo "# DONE!"
echo "# Installing Go"
su -l $ME -c "\
  curl 'https://dl.google.com/go/go1.23.3.linux-amd64.tar.gz' -o go.tar.gz \
  && sudo -S tar -C /usr/local -xzf go.tar.gz \
  && rm go.tar.gz \
"
echo "# DONE!"
echo "# Installing Discord"
su -l $ME -c "\
  curl 'https://stable.dl2.discordapp.net/apps/linux/0.0.75/discord-0.0.75.deb' -o discord.deb \
  && sudo -S apt install --yes ./discord.deb \
  && rm discord.deb
"
echo "# DONE!"
echo "# Configuring some stuff..."
chsh -s /usr/bin/fish
fish -c "mkdir -p $HOME/.config/{fish/completions, nvim, git, tmux}"
fish -c "mkdir -p $HOME/.local/{python, ipython, jupyter}"
fish -c "mkdir -p $HOME/{avi, dev, doc, jpg, tmp, var, wav}"
git config --add --global user.name "$ME"
git config --add --global user.email "$ME@pm.me"
git config --add --global init.defaultBranch main
mv .gitconfig $HOME/.config/git/config
git clone https://github.com/neovim/nvim-lspconfig $HOME/.config/nvim/pack/nvim/start/nvim-lspconfig
echo "require("lspconfig").gopls.setup({})\nrequire("lspconfig").ruff.setup({})" > $HOME/.config/nvim/init.lua
echo "set -g base-index 1\nsetw -g pane-base-index 1" > $HOME/.config/tmux/tmux.conf
touch $HOME/.local/python/history
fish -c "set -Ux LESSHISTFILE -"
fish -c "set -Ux PYTHON_HISTORY $HOME/.local/python/history"
fish -c "set -Ux JUPYTER_CONFIG_DIR $HOME/.local/jupyter"
fish -c "set -Ux IPYTHONDIR $HOME/.local/ipython"
fish -c "set -Ux GOPATH $HOME/.local/go"
fish -c "set -Ux GOBIN $HOME/.local/go/bin"
fish -c "fish_add_path /usr/local/go/bin"
fish -c "fish_add_path $HOME/.local/bin"
fish -c "fish_add_path $HOME/.local/go/bin"
fish -c "fish_add_path $HOME/.cargo/bin"
fish -c "uv generate-shell-completion fish > $HOME/.config/fish/completions/uv.fish"
fish -c "uvx --generate-shell-completion fish > $HOME/.config/fish/completions/uvx.fish"
fish -c "ruff generate-shell-completion fish > $HOME/.config/fish/completions/ruff.fish"
fish -c "go install golang.org/x/tools/gopls@latest"
fish -c "abbr --add vi nvim"
fish -c "abbr --add vim nvim"
echo "# ALL DONE!"
